### ISSUE TITLE
Melhorar a forma como se lida com erros nos requests

### ISSUE THREAD

**Issue by hugomaiavieira** [DeveloperCielo/API-3.0-Ruby#5]
Se fizermos o seguinte request (onde o `payment_id` está no padrão correto mas não existe):

``` ruby
client.get_sale("7e1503c6-8ad7-46fc-8a35-6da99932b5a2")
```

Vamos ter o erro abaixo ([nesta linha](https://github.com/DeveloperCielo/API-3.0-Ruby/blob/master/lib/cielo/api30/request/cielo_request.rb#L38)):

```
JSON::ParserError: A JSON text must at least contain two octets!
  from /home/hugo/.gem/repos/cobrato/bundler/gems/API-3.0-Ruby-7ebbc0e866a2/lib/cielo/api30/request/cielo_request.rb:38:in `send_request'
```

Pois a resposta terá o código 404 e o corpo vazio.

---

Se fizermos o seguinte request (onde o `payment_id` não está no padrão)

``` ruby
client.get_sale("7e1503c6-8ad7-46fc-8a35")
```

Vamos ter o erro abaixo ([nesta linha](https://github.com/DeveloperCielo/API-3.0-Ruby/blob/master/lib/cielo/api30/request/cielo_request.rb#L40)):

```
TypeError: no implicit conversion of String into Integer
	from /home/hugo/.gem/repos/cobrato/bundler/gems/API-3.0-Ruby-7ebbc0e866a2/lib/cielo/api30/request/cielo_request.rb:40:in `[]'
	from /home/hugo/.gem/repos/cobrato/bundler/gems/API-3.0-Ruby-7ebbc0e866a2/lib/cielo/api30/request/cielo_request.rb:40:in `send_request'
```

Pois a resposta terá o código 400 e o corpo:

``` ruby
{"Message"=>"The request is invalid.",
 "MessageDetail"=>
  "The parameters dictionary contains a null entry for parameter 'paymentId' of non-nullable type 'System.Guid' for method 'System.Web.Http.IHttpActionResult GetTransaction(System.Guid)' in 'Cielo.ApiQuery.Controllers.V1.SaleCieloV1Controller'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter."}
```

Pois retornará `nil` para o método `first` e depois será chamado o `[]`.

**Comment by Hamdan85** [comment]
eu estou recebendo esse erro para o create_sale...

**Comment by detierno** [comment]
recebendo o mesmo erro aqui

**Comment by fagianijunior** [comment]
Para mim também, tanto no get_sale quanto no create_sale. Alguém conseguiu uma solução?
